// File generated by FlutterFire CLI.
// ARBORIS CORE - Firebase Configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG9rWlByvtGu_2oCdjulrOY5NMO-qXTzs',
    appId: '1:537123553346:web:35a1080cda3509861b6ddb',
    messagingSenderId: '537123553346',
    projectId: 'arboris-core',
    authDomain: 'arboris-core.firebaseapp.com',
    storageBucket: 'arboris-core.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9rWlByvtGu_2oCdjulrOY5NMO-qXTzs',
    appId: '1:537123553346:android:a2d045e02c70450a1b6ddb',
    messagingSenderId: '537123553346',
    projectId: 'arboris-core',
    authDomain: 'arboris-core.firebaseapp.com',
    storageBucket: 'arboris-core.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9rWlByvtGu_2oCdjulrOY5NMO-qXTzs',
    appId: '1:537123553346:ios:bf4cfafdb04b9e451b6ddb',
    messagingSenderId: '537123553346',
    projectId: 'arboris-core',
    authDomain: 'arboris-core.firebaseapp.com',
    storageBucket: 'arboris-core.firebasestorage.app',
    iosClientId: '537123553346-m5bv9uj1bf6bfb17p7344b03t291ir1g.apps.googleusercontent.com',
    iosBundleId: 'ai.arboris.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9rWlByvtGu_2oCdjulrOY5NMO-qXTzs',
    appId: '1:537123553346:ios:bf4cfafdb04b9e451b6ddb',
    messagingSenderId: '537123553346',
    projectId: 'arboris-core',
    authDomain: 'arboris-core.firebaseapp.com',
    storageBucket: 'arboris-core.firebasestorage.app',
    iosClientId: '537123553346-m5bv9uj1bf6bfb17p7344b03t291ir1g.apps.googleusercontent.com',
    iosBundleId: 'ai.arboris.app',
  );
}
